"""State extraction helpers for cross-domain coordination in Phase 2 combined step"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/helpers.ipynb.

# %% auto #0
__all__ = ['SEG_DEFAULT_VISIBLE_COUNT', 'SEG_DEFAULT_CARD_WIDTH', 'ALIGN_DEFAULT_VISIBLE_COUNT', 'ALIGN_DEFAULT_CARD_WIDTH',
           'check_alignment_ready', 'extract_seg_state', 'extract_alignment_state', 'get_segment_count',
           'get_chunk_count']

# %% ../../nbs/components/helpers.ipynb #c3d4e5f6
from typing import Any, Dict, List, Optional

from cjm_fasthtml_interactions.core.context import InteractionContext
from cjm_fasthtml_card_stack.core.constants import DEFAULT_VISIBLE_COUNT, DEFAULT_CARD_WIDTH

from cjm_transcript_segmentation.models import TextSegment
from cjm_transcript_vad_align.models import VADChunk

# %% ../../nbs/components/helpers.ipynb #e5f6a7b8
def check_alignment_ready(
    segment_count:int,  # Number of text segments
    chunk_count:int,  # Number of VAD chunks
) -> bool:  # True if counts match for 1:1 alignment
    """Check if segment and VAD chunk counts match for 1:1 alignment."""
    return segment_count > 0 and chunk_count > 0 and segment_count == chunk_count

# %% ../../nbs/components/helpers.ipynb #a7b8c9d0
# Default values for segmentation card stack (wider cards for text)
SEG_DEFAULT_VISIBLE_COUNT = 3
SEG_DEFAULT_CARD_WIDTH = 80

# %% ../../nbs/components/helpers.ipynb #b8c9d0e1
def extract_seg_state(
    ctx:InteractionContext,  # Interaction context with state
) -> Dict[str, Any]:  # Extracted state values
    """Extract segmentation state as explicit values for renderers."""
    state = ctx.state.get("step_states", {}).get("segmentation", {})
    return {
        "is_initialized": state.get("is_initialized", False),
        "segments": [TextSegment.from_dict(s) for s in state.get("segments", [])],
        "focused_index": state.get("focused_index", 0),
        "visible_count": state.get("visible_count", SEG_DEFAULT_VISIBLE_COUNT),
        "card_width": state.get("card_width", SEG_DEFAULT_CARD_WIDTH),
        "history": state.get("history", []),
        "is_auto_mode": state.get("is_auto_mode", False),
    }

# %% ../../nbs/components/helpers.ipynb #d0e1f2a3
# Default values for alignment card stack (compact cards for VAD chunks)
ALIGN_DEFAULT_VISIBLE_COUNT = 5
ALIGN_DEFAULT_CARD_WIDTH = 40

# %% ../../nbs/components/helpers.ipynb #e1f2a3b4
def extract_alignment_state(
    ctx:InteractionContext,  # Interaction context with state
) -> Dict[str, Any]:  # Extracted state values
    """Extract alignment state as explicit values for renderers."""
    state = ctx.state.get("step_states", {}).get("alignment", {})
    return {
        "is_initialized": state.get("is_initialized", False),
        "vad_chunks": [VADChunk.from_dict(c) for c in state.get("vad_chunks", [])],
        "focused_index": state.get("focused_chunk_index", 0),
        "visible_count": state.get("visible_count", ALIGN_DEFAULT_VISIBLE_COUNT),
        "card_width": state.get("card_width", ALIGN_DEFAULT_CARD_WIDTH),
        "media_path": state.get("media_path"),
        "media_paths": state.get("media_paths", []),
        "audio_duration": state.get("audio_duration"),
        "is_auto_mode": state.get("is_auto_mode", False),
    }

# %% ../../nbs/components/helpers.ipynb #a3b4c5d6
def get_segment_count(
    ctx:InteractionContext,  # Interaction context with state
) -> int:  # Number of segments
    """Get segment count from state without full extraction."""
    state = ctx.state.get("step_states", {}).get("segmentation", {})
    return len(state.get("segments", []))


def get_chunk_count(
    ctx:InteractionContext,  # Interaction context with state
) -> int:  # Number of VAD chunks
    """Get VAD chunk count from state without full extraction."""
    state = ctx.state.get("step_states", {}).get("alignment", {})
    return len(state.get("vad_chunks", []))
