"""Synced navigation toggle for the combined Phase 2 dual-column step"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/sync_controls.ipynb.

# %% auto #0
__all__ = ['SYNC_TOGGLE_FN', 'SYNC_KEY', 'SYNC_BTN_ID', 'SHOULD_PLAY_FN', 'render_sync_toggle_button', 'generate_sync_script',
           'generate_sync_key_toggle_js', 'generate_should_play_js', 'generate_sync_restore_js', 'build_extra_actions']

# %% ../../nbs/components/sync_controls.ipynb #sync-imports
from typing import Any

from fasthtml.common import Button, Script

from cjm_fasthtml_daisyui.components.actions.button import btn, btn_sizes, btn_styles, btn_colors
from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui
from cjm_fasthtml_tailwind.utilities.spacing import m
from cjm_fasthtml_tailwind.core.base import combine_classes

from cjm_fasthtml_lucide_icons.factory import lucide_icon

# Design system recipes (V11 icon-size roles)
from cjm_fasthtml_design_system.icons import icons

from cjm_fasthtml_card_stack.js.sync import generate_card_stack_sync_js

# %% ../../nbs/components/sync_controls.ipynb #sync-consts
# JS function name for toggling sync (called by KeyAction wrapper)
SYNC_TOGGLE_FN = "toggleSegAlignSync"

# Window key for sync state + cleanup
SYNC_KEY = "_segAlignSync"

# HTML ID for the toolbar sync toggle button
SYNC_BTN_ID = "sd-sync-toggle-btn"

# %% ../../nbs/components/sync_controls.ipynb #sync-btn
def render_sync_toggle_button() -> Any:  # Sync toggle button element
    """Render the synced navigation toggle button for the seg toolbar."""
    return Button(
        lucide_icon("link", size=icons.text_button, cls=str(m.r(1))),
        "Sync",
        id=SYNC_BTN_ID,
        type="button",
        cls=combine_classes(btn, btn_sizes.sm, btn_styles.outline),
        onclick=(
            f"var on=window.{SYNC_TOGGLE_FN}&&window.{SYNC_TOGGLE_FN}();"
            f"this.classList.toggle('btn-primary',on);"
            f"this.classList.toggle('btn-outline',!on);"
        ),
    )

# %% ../../nbs/components/sync_controls.ipynb #sync-js
def generate_sync_script(
    source_input_id:str,  # Seg card stack's focused_index hidden input ID
    target_nav_url:str,  # Align card stack's nav_to_index URL
) -> Any:  # Script element with sync JS
    """Generate the sync JS Script element for the combined step."""
    return Script(generate_card_stack_sync_js(
        source_input_id=source_input_id,
        target_nav_url=target_nav_url,
        toggle_fn_name=SYNC_TOGGLE_FN,
        sync_key=SYNC_KEY,
    ))

# %% ../../nbs/components/sync_controls.ipynb #sync-key-js
def generate_sync_key_toggle_js() -> str:  # JS defining window._segAlignSyncKeyToggle
    """Generate JS for the S key sync toggle wrapper function."""
    return f"""
    window._segAlignSyncKeyToggle = function() {{
        var on = window.{SYNC_TOGGLE_FN} && window.{SYNC_TOGGLE_FN}();
        var btn = document.getElementById('{SYNC_BTN_ID}');
        if (btn) {{
            btn.classList.toggle('btn-primary', on);
            btn.classList.toggle('btn-outline', !on);
        }}
    }};
    """

# %% ../../nbs/components/sync_controls.ipynb #c5jqc9txw6
# Function name passed to WebAudioConfig.should_play_fn via vad-align
SHOULD_PLAY_FN = "shouldAlignPlay"

def generate_should_play_js() -> str:  # JS defining window.shouldAlignPlay
    """Generate JS for the custom play guard function.
    
    Returns true when audio should play:
    - Zone is active (direct align navigation), OR
    - Auto-navigate is on (auto-play through align stack), OR
    - Sync is enabled (seg navigation driving align)
    """
    from cjm_transcript_vad_align.components.callbacks import ALIGN_AUDIO_CONFIG
    sk = ALIGN_AUDIO_CONFIG.state_key
    return f"""
    window.{SHOULD_PLAY_FN} = function(cardStackId) {{
        // Zone active check
        var zoneActive = true;
        if (window.kbNav) {{
            var kbState = window.kbNav.getState();
            if (kbState) zoneActive = (kbState.activeZoneId === cardStackId);
        }}
        if (zoneActive) return true;

        // Auto-navigate check
        if (window.{sk} && window.{sk}.autoNavigate) return true;

        // Sync enabled check
        if (window.{SYNC_KEY} && window.{SYNC_KEY}.enabled) return true;

        return false;
    }};"""

# %% ../../nbs/components/sync_controls.ipynb #6l3m1ira3gd
def generate_sync_restore_js() -> str:  # JS to restore sync button styling from client state
    """Generate JS to sync the toolbar button styling with the client-side sync state.
    
    After chrome switch re-renders the seg toolbar, the sync button starts
    with btn-outline. This reads the JS state and restores btn-primary if
    sync is enabled.
    """
    return f"""
        var _sb = document.getElementById('{SYNC_BTN_ID}');
        if (_sb && window.{SYNC_KEY}) {{
            var _on = window.{SYNC_KEY}.enabled || false;
            _sb.classList.toggle('btn-primary', _on);
            _sb.classList.toggle('btn-outline', !_on);
        }}
    """

# %% ../../nbs/components/sync_controls.ipynb #mggeymhntih
def build_extra_actions(
    fa_extra:Any=None,  # FA controls element (from build_fa_extra_actions, or None)
) -> tuple:  # Tuple of toolbar extra action elements
    """Build the extra_actions tuple for the seg toolbar.
    
    Combines FA controls (if available) with the sync toggle button.
    Client-side state restoration (sync button styling) is handled by
    the centralized toolbar restore settle handler in toolbar_state.py.
    Returns a tuple compatible with render_toolbar(extra_actions=...).
    """
    actions = []
    if fa_extra is not None:
        actions.append(fa_extra)
    actions.append(render_sync_toggle_button())
    return tuple(actions)
