"""Centralized client-side toolbar state restoration after HTMX settles"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/toolbar_state.ipynb.

# %% auto #0
__all__ = ['generate_toolbar_restore_js']

# %% ../../nbs/components/toolbar_state.ipynb #ts-imports
from fasthtml.common import Script

from cjm_transcript_segment_align.components.sync_controls import (
    SYNC_KEY, SYNC_BTN_ID,
)
from cjm_transcript_vad_align.components.audio_controls import (
    AlignAudioControlIds, _TOGGLE_BG_OFF, _TOGGLE_BG_ON,
)
from cjm_transcript_vad_align.components.callbacks import ALIGN_AUDIO_CONFIG

# %% ../../nbs/components/toolbar_state.ipynb #ts-gen
# Unique key for the settle handler on window (for cleanup)
_TOOLBAR_RESTORE_KEY = "_sdToolbarRestoreHandler"


def generate_toolbar_restore_js() -> Script:  # Script element with settle handler
    """Generate the centralized toolbar state restore settle handler.
    
    Restores client-side state for all toolbar toggles/buttons after any
    HTMX settle that re-renders the toolbar. Runs once per settle event.
    """
    sk = ALIGN_AUDIO_CONFIG.state_key
    toggle_id = AlignAudioControlIds.AUTO_NAV_TOGGLE

    return Script(f"""
    (function() {{
        // Clean up previous handler
        if (window.{_TOOLBAR_RESTORE_KEY}) {{
            document.body.removeEventListener('htmx:afterSettle', window.{_TOOLBAR_RESTORE_KEY});
        }}

        function restoreToolbarState() {{
            // --- Sync button: btn-primary (on) / btn-outline (off) ---
            var syncBtn = document.getElementById('{SYNC_BTN_ID}');
            if (syncBtn && window.{SYNC_KEY}) {{
                var syncOn = window.{SYNC_KEY}.enabled || false;
                syncBtn.classList.toggle('btn-primary', syncOn);
                syncBtn.classList.toggle('btn-outline', !syncOn);
            }}

            // --- Auto-play toggle: checked + bg-success (on) / bg-error (off) ---
            var autoToggle = document.getElementById('{toggle_id}');
            if (autoToggle && window.{sk}) {{
                var autoOn = window.{sk}.autoNavigate || false;
                autoToggle.checked = autoOn;
                autoToggle.classList.remove('{_TOGGLE_BG_OFF}', '{_TOGGLE_BG_ON}');
                autoToggle.classList.add(autoOn ? '{_TOGGLE_BG_ON}' : '{_TOGGLE_BG_OFF}');
            }}
        }}

        window.{_TOOLBAR_RESTORE_KEY} = function(evt) {{
            restoreToolbarState();
        }};
        document.body.addEventListener('htmx:afterSettle', window.{_TOOLBAR_RESTORE_KEY});
    }})();
    """)
