"""Shared chrome switching route handlers for the combined Phase 2 step"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/chrome.ipynb.

# %% auto #0
__all__ = ['DEBUG_SWITCH_CHROME', 'init_chrome_router']

# %% ../../nbs/routes/chrome.ipynb #c3d4e5f6
from typing import Tuple, Dict, Callable

from fasthtml.common import APIRouter, Div

from cjm_fasthtml_card_stack.components.settings_modal import render_settings_trigger
from cjm_fasthtml_card_stack.core.constants import DEFAULT_VISIBLE_COUNT, DEFAULT_CARD_WIDTH

from cjm_fasthtml_interactions.core.state_store import get_session_id

from cjm_workflow_state.state_store import SQLiteWorkflowStateStore

from ..html_ids import CombinedHtmlIds
from cjm_transcript_segmentation.models import TextSegment, SegmentationUrls
from cjm_transcript_vad_align.models import VADChunk, AlignmentUrls

# Segmentation renderers
from cjm_transcript_segmentation.components.step_renderer import (
    render_toolbar as render_seg_toolbar,
    render_seg_footer_content,
)
from cjm_transcript_segmentation.components.card_stack_config import (
    SEG_CS_CONFIG, SEG_CS_IDS,
)

# Alignment renderers
from cjm_transcript_vad_align.components.step_renderer import (
    render_align_toolbar, render_align_footer_content,
)
from cjm_transcript_vad_align.components.card_stack_config import (
    ALIGN_CS_CONFIG, ALIGN_CS_IDS,
)

from cjm_fasthtml_tailwind.utilities.sizing import w
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, items, gap,
)
from cjm_fasthtml_tailwind.core.base import combine_classes

# Footer helper + FA extra_actions builder + match detection
from cjm_transcript_segment_align.components.step_renderer import (
    render_footer_inner_content,
)
from cjm_transcript_segment_align.components.handlers import (
    build_fa_extra_actions, segments_match_presplit,
)
from ..components.sync_controls import build_extra_actions


DEBUG_SWITCH_CHROME = False

# %% ../../nbs/routes/chrome.ipynb #e5f6a7b8
async def _handle_switch_chrome(
    state_store:SQLiteWorkflowStateStore,  # State store instance
    workflow_id:str,  # Workflow identifier
    request,  # FastHTML request object
    sess,  # FastHTML session object
    seg_urls:SegmentationUrls,  # URL bundle for segmentation routes
    align_urls:AlignmentUrls,  # URL bundle for alignment routes
    jm_trigger=None,  # Pre-rendered job monitor trigger element
    fa_toggle_url:str="",  # URL for FA toggle route
    fa_available:bool=False,  # Whether FA plugin is available
) -> tuple:  # OOB swaps for shared chrome containers
    """Switch shared chrome content based on active column.
    
    Client-side toolbar state restoration (sync button, auto-play toggle)
    is handled by the centralized settle handler from toolbar_state.py.
    Settings modals persist in the DOM — only the trigger buttons swap.
    """
    form = await request.form()
    active_column = form.get("active_column", "seg")

    if DEBUG_SWITCH_CHROME:
        print(f"[SWITCH_CHROME] active_column: {active_column}")

    session_id = get_session_id(sess)
    state = state_store.get_state(workflow_id, session_id)
    step_states = state.get("step_states", {})
    seg_state = step_states.get("segmentation", {})
    align_state = step_states.get("alignment", {})

    # Get counts for alignment status
    segment_count = len(seg_state.get("segments", []))
    chunk_count = len(align_state.get("vad_chunks", []))

    if active_column == "seg":
        # Segmentation chrome (settings trigger + toolbar)
        segments = [TextSegment.from_dict(s) for s in seg_state.get("segments", [])]
        history = seg_state.get("history", [])
        focused_index = seg_state.get("focused_index", 0)

        # Build FA extra_actions and NLTK Split disabled state
        fa_extra = build_fa_extra_actions(
            seg_state, jm_trigger, fa_toggle_url, fa_available,
        )
        nltk_presplit = seg_state.get("nltk_presplit", [])
        nltk_disabled = segments_match_presplit(
            seg_state.get("segments", []), nltk_presplit,
        )

        settings_trigger = render_settings_trigger(modal_id=SEG_CS_IDS.settings_modal)
        toolbar_content = Div(
            settings_trigger,
            render_seg_toolbar(
                reset_url=seg_urls.reset,
                ai_split_url=seg_urls.ai_split,
                undo_url=seg_urls.undo,
                can_undo=(len(history) > 0),
                extra_actions=build_extra_actions(fa_extra),
                nltk_split_disabled=nltk_disabled,
            ),
            cls=combine_classes(flex_display, items.center, gap(2), w.full),
        )
    else:
        # Alignment chrome (settings trigger + speed selector + auto-play toggle)
        # Read persisted state so chrome switches restore the user's current speed + auto-nav
        settings_trigger = render_settings_trigger(modal_id=ALIGN_CS_IDS.settings_modal)
        toolbar_content = Div(
            settings_trigger,
            render_align_toolbar(
                current_speed=align_state.get("playback_speed", 1.0),
                auto_navigate=align_state.get("auto_navigate", False),
                speed_url=align_urls.speed_change,
            ),
            cls=combine_classes(flex_display, items.center, gap(2), w.full),
        )

    # --- Footer: both column footers always present ---
    seg_segments = [TextSegment.from_dict(s) for s in seg_state.get("segments", [])]
    seg_focused = seg_state.get("focused_index", 0)
    seg_footer = render_seg_footer_content(seg_segments, seg_focused) if seg_segments else None

    align_chunks = [VADChunk.from_dict(c) for c in align_state.get("vad_chunks", [])]
    align_focused = align_state.get("focused_chunk_index", 0)
    align_footer = render_align_footer_content(align_chunks, align_focused) if align_chunks else None

    if DEBUG_SWITCH_CHROME:
        print(f"[SWITCH_CHROME] returning OOB swaps for {active_column}")

    # Return OOB swaps (toolbar + footer — settings modals persist in DOM)
    toolbar_oob = Div(
        toolbar_content,
        id=CombinedHtmlIds.SHARED_TOOLBAR,
        hx_swap_oob="innerHTML"
    )
    footer_oob = Div(
        render_footer_inner_content(seg_footer, align_footer, segment_count, chunk_count),
        id=CombinedHtmlIds.SHARED_FOOTER,
        hx_swap_oob="innerHTML"
    )

    return (toolbar_oob, footer_oob)

# %% ../../nbs/routes/chrome.ipynb #g7b8c9d0
def init_chrome_router(
    state_store: SQLiteWorkflowStateStore,  # State store instance
    workflow_id: str,  # Workflow identifier
    seg_urls: SegmentationUrls,  # URL bundle for segmentation routes
    align_urls: AlignmentUrls,  # URL bundle for alignment routes
    prefix: str,  # Route prefix (e.g., "/workflow/core/chrome")
    jm_trigger = None,  # Pre-rendered job monitor trigger element
    fa_toggle_url: str = "",  # URL for FA toggle route
    fa_available: bool = False,  # Whether FA plugin is available
) -> Tuple[APIRouter, Dict[str, Callable]]:  # (router, route_dict)
    """Initialize chrome switching routes."""
    router = APIRouter(prefix=prefix)

    @router
    async def switch_chrome(request, sess):
        """Switch shared chrome content based on active column."""
        return await _handle_switch_chrome(
            state_store, workflow_id, request, sess,
            seg_urls=seg_urls,
            align_urls=align_urls,
            jm_trigger=jm_trigger,
            fa_toggle_url=fa_toggle_url,
            fa_available=fa_available,
        )

    routes = {
        "switch_chrome": switch_chrome,
    }

    return router, routes
