"""Routes for triggering forced alignment, polling progress, and toggling between NLTK and force-aligned pre-splits"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/forced_alignment.ipynb.

# %% auto #0
__all__ = ['FA_SLOT_ID', 'render_fa_trigger_button', 'render_fa_progress', 'render_fa_toggle', 'init_forced_alignment_routers']

# %% ../../nbs/routes/forced_alignment.ipynb #cell-imports
from typing import Any, Dict, List, Tuple, Callable, Optional
from dataclasses import asdict

from fasthtml.common import Div, Span, Button, Progress, APIRouter

from cjm_fasthtml_interactions.core.state_store import get_session_id
from cjm_fasthtml_daisyui.components.actions.button import btn, btn_colors, btn_sizes, btn_styles
from cjm_fasthtml_daisyui.components.feedback.loading import loading, loading_styles, loading_sizes
from cjm_fasthtml_daisyui.components.feedback.progress import progress as progress_cls, progress_colors
from cjm_fasthtml_daisyui.components.layout.join import join, join_item
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.typography import font_size
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import flex_display, items, gap
from cjm_fasthtml_tailwind.core.base import combine_classes
from cjm_fasthtml_lucide_icons.factory import lucide_icon

from cjm_workflow_state.state_store import SQLiteWorkflowStateStore
from cjm_fasthtml_card_stack.core.constants import DEFAULT_VISIBLE_COUNT
from cjm_transcript_segmentation.models import TextSegment, SegmentationUrls
from cjm_transcript_segmentation.routes.handlers import build_mutation_response
from cjm_transcript_vad_align.models import VADChunk
from cjm_transcript_source_select.services.source import SourceService

from ..html_ids import CombinedHtmlIds
from cjm_transcript_segment_align.components.step_renderer import (
    render_alignment_status, render_seg_mini_stats_badge,
)
from ..services.forced_alignment import ForcedAlignmentService

# %% ../../nbs/routes/forced_alignment.ipynb #cell-ids
# Stable ID for FA controls area within toolbar (progress polling target)
FA_SLOT_ID = CombinedHtmlIds.FA_TOOLBAR_SLOT

# %% ../../nbs/routes/forced_alignment.ipynb #cell-render-button
def render_fa_trigger_button(
    trigger_url: str,  # URL for forced alignment trigger route
    disabled: bool = False,  # Whether button is disabled
) -> Any:  # Force Align trigger button
    """Render the Force Align trigger button."""
    return Button(
        lucide_icon("audio-waveform", size=4, cls=str(m.r(2))),
        "Force Align",
        cls=combine_classes(btn, btn_colors.primary, btn_sizes.sm),
        disabled="disabled" if disabled else None,
        hx_post=trigger_url,
        hx_swap="none",
    )

# %% ../../nbs/routes/forced_alignment.ipynb #cell-render-progress
def render_fa_progress(
    progress_val: float,  # Progress value 0.0-1.0
    message: str,  # Progress stage message
    progress_url: str,  # URL for progress polling
) -> Any:  # Progress indicator with polling
    """Render forced alignment progress indicator with HTMX polling."""
    pct = int(progress_val * 100)
    return Div(
        Div(
            Span(cls=combine_classes(loading, loading_styles.spinner, loading_sizes.sm)),
            Span(
                f"{message} ({pct}%)",
                cls=combine_classes(font_size.sm, m.l(2))
            ),
            cls=combine_classes(flex_display, items.center)
        ),
        Progress(
            value=str(pct), max="100",
            cls=combine_classes(progress_cls, progress_colors.primary, "w-48")
        ),
        hx_get=progress_url,
        hx_trigger="every 1s",
        hx_target=f"#{FA_SLOT_ID}",
        hx_swap="innerHTML",
        cls=combine_classes(flex_display, items.center, gap(3)),
    )

# %% ../../nbs/routes/forced_alignment.ipynb #cell-render-toggle
def render_fa_toggle(
    active_presplit: str,  # "nltk" or "forced_alignment"
    toggle_url: str,  # URL for toggle route
) -> Any:  # Toggle button group
    """Render the NLTK / Force Aligned toggle button group."""
    nltk_active = active_presplit == "nltk"
    fa_active = active_presplit == "forced_alignment"

    nltk_cls = combine_classes(
        btn, btn_sizes.sm, join_item,
        btn_colors.primary if nltk_active else btn_styles.outline
    )
    fa_cls = combine_classes(
        btn, btn_sizes.sm, join_item,
        btn_colors.primary if fa_active else btn_styles.outline
    )

    return Div(
        Span("Pre-splits:", cls=combine_classes(font_size.sm, m.r(2))),
        Div(
            Button(
                lucide_icon("text-cursor-input", size=4, cls=str(m.r(1))),
                "NLTK",
                cls=nltk_cls,
                hx_post=toggle_url,
                hx_vals='{"mode": "nltk"}',
                hx_swap="none",
                disabled="disabled" if nltk_active else None,
            ),
            Button(
                lucide_icon("audio-waveform", size=4, cls=str(m.r(1))),
                "Force Aligned",
                cls=fa_cls,
                hx_post=toggle_url,
                hx_vals='{"mode": "forced_alignment"}',
                hx_swap="none",
                disabled="disabled" if fa_active else None,
            ),
            cls=join,
        ),
        cls=combine_classes(flex_display, items.center),
    )

# %% ../../nbs/routes/forced_alignment.ipynb #cell-handler-trigger
async def _handle_fa_trigger(
    state_store: SQLiteWorkflowStateStore,
    workflow_id: str,
    fa_service: ForcedAlignmentService,
    source_service: SourceService,
    request: Any,
    sess: Any,
    seg_urls: SegmentationUrls,
    toggle_url: str,
) -> Any:  # Targeted OOB updates (slots + stats + toolbar with toggle + alignment status + mini-stats)
    """Trigger forced alignment and replace working segments with FA splits."""
    session_id = get_session_id(sess)
    state = state_store.get_state(workflow_id, session_id)
    step_states = state.get("step_states", {})
    seg_state = step_states.get("segmentation", {})
    align_state = step_states.get("alignment", {})
    selection_state = step_states.get("selection", {})

    # Get VAD chunks (must be initialized)
    vad_chunk_dicts = align_state.get("vad_chunks", [])
    if not vad_chunk_dicts:
        return ()

    vad_chunks = [VADChunk.from_dict(c) for c in vad_chunk_dicts]

    # Get source info for audio paths and text
    selected_sources = selection_state.get("selected_sources", [])
    source_blocks = source_service.get_source_blocks(selected_sources)

    # Build audio paths from source blocks
    audio_paths = []
    for src in selected_sources:
        block = source_service.get_transcription_by_id(src["record_id"], src["provider_id"])
        audio_paths.append(block.media_path)

    # Group VAD chunks by source (using audio_file_index if available)
    if len(source_blocks) == 1:
        vad_chunks_by_source = [vad_chunks]
    else:
        chunks_by_idx: Dict[int, List[VADChunk]] = {}
        for chunk in vad_chunks:
            idx = getattr(chunk, 'audio_file_index', 0)
            if idx not in chunks_by_idx:
                chunks_by_idx[idx] = []
            chunks_by_idx[idx].append(chunk)
        vad_chunks_by_source = [chunks_by_idx.get(i, []) for i in range(len(source_blocks))]

    # Run forced alignment (synchronous for now — Phase 6 adds async with progress)
    fa_segments = await fa_service.align_and_split_combined_async(
        source_blocks=source_blocks,
        audio_paths=audio_paths,
        vad_chunks_by_source=vad_chunks_by_source,
    )

    # Store FA segments as fa_presplit snapshot and set as current
    fa_seg_dicts = [asdict(s) for s in fa_segments]
    seg_state["fa_presplit"] = fa_seg_dicts[:]
    seg_state["segments"] = fa_seg_dicts
    seg_state["initial_segments"] = fa_seg_dicts[:]
    seg_state["focused_index"] = 0
    seg_state["history"] = []

    # Clean up old state fields if present (migration from old model)
    for key in ("active_presplit", "nltk_segments", "nltk_initial_segments",
                "fa_segments", "fa_initial_segments"):
        seg_state.pop(key, None)

    step_states["segmentation"] = seg_state
    state["step_states"] = step_states
    state_store.update_state(workflow_id, session_id, state)

    # Build FA toggle for toolbar extra_actions
    fa_toggle = Div(
        render_fa_toggle("forced_alignment", toggle_url),
        id=FA_SLOT_ID,
    )

    # Build targeted mutation response (same pattern as split/merge)
    seg_oob = build_mutation_response(
        segment_dicts=fa_seg_dicts,
        focused_index=0,
        visible_count=seg_state.get("visible_count", DEFAULT_VISIBLE_COUNT),
        history_depth=0,
        urls=seg_urls,
        extra_actions=fa_toggle,
        nltk_split_disabled=False,  # FA pre-split ≠ NLTK pre-split
    )

    # Cross-domain OOB
    segment_count = len(fa_segments)
    chunk_count = len(vad_chunk_dicts)
    alignment_status_oob = render_alignment_status(segment_count, chunk_count, oob=True)
    mini_stats_oob = render_seg_mini_stats_badge(fa_segments, oob=True)

    return (*seg_oob, alignment_status_oob, mini_stats_oob)

# %% ../../nbs/routes/forced_alignment.ipynb #cell-handler-toggle
async def _handle_fa_toggle(
    state_store: SQLiteWorkflowStateStore,
    workflow_id: str,
    request: Any,
    sess: Any,
    seg_urls: SegmentationUrls,
    toggle_url: str,
) -> Any:  # Targeted OOB updates (slots + stats + toolbar with toggle + alignment status + mini-stats)
    """Toggle between NLTK and force-aligned pre-split snapshots.
    
    Loads the selected pre-split snapshot as the current working state.
    Pushes the previous working state to undo history (single history model).
    """
    from cjm_transcript_segment_align.components.handlers import segments_match_presplit
    from cjm_workflow_state.history import push_history

    form = await request.form()
    target_mode = form.get("mode", "nltk")

    session_id = get_session_id(sess)
    state = state_store.get_state(workflow_id, session_id)
    step_states = state.get("step_states", {})
    seg_state = step_states.get("segmentation", {})
    align_state = step_states.get("alignment", {})

    nltk_presplit = seg_state.get("nltk_presplit", [])
    fa_presplit = seg_state.get("fa_presplit", [])
    current_segments = seg_state.get("segments", [])

    # Determine which snapshot to load
    if target_mode == "nltk":
        target_segments = nltk_presplit
    else:
        target_segments = fa_presplit

    # No-op if current already matches target
    if segments_match_presplit(current_segments, target_segments):
        return ()

    # Push current state to undo history before switching
    history = seg_state.get("history", [])
    focused_index = seg_state.get("focused_index", 0)
    snapshot = {"segments": current_segments, "focused_index": focused_index}
    history = push_history(history, snapshot, max_depth=20)

    # Load target snapshot as current working state
    seg_state["segments"] = target_segments[:]
    seg_state["initial_segments"] = target_segments[:]
    seg_state["focused_index"] = 0
    seg_state["history"] = history

    step_states["segmentation"] = seg_state
    state["step_states"] = step_states
    state_store.update_state(workflow_id, session_id, state)

    # Build FA toggle for toolbar extra_actions
    fa_toggle_content = Div(
        render_fa_toggle(target_mode, toggle_url),
        id=FA_SLOT_ID,
    )

    # NLTK Split disabled when target is NLTK
    nltk_disabled = (target_mode == "nltk")

    # Build targeted mutation response
    seg_oob = build_mutation_response(
        segment_dicts=target_segments,
        focused_index=0,
        visible_count=seg_state.get("visible_count", DEFAULT_VISIBLE_COUNT),
        history_depth=len(history),
        urls=seg_urls,
        extra_actions=fa_toggle_content,
        nltk_split_disabled=nltk_disabled,
    )

    # Cross-domain OOB
    segments = [TextSegment.from_dict(s) for s in target_segments]
    chunk_count = len(align_state.get("vad_chunks", []))
    alignment_status_oob = render_alignment_status(len(segments), chunk_count, oob=True)
    mini_stats_oob = render_seg_mini_stats_badge(segments, oob=True)

    return (*seg_oob, alignment_status_oob, mini_stats_oob)

# %% ../../nbs/routes/forced_alignment.ipynb #cell-router
def init_forced_alignment_routers(
    state_store: SQLiteWorkflowStateStore,  # State store instance
    workflow_id: str,  # Workflow identifier
    fa_service: ForcedAlignmentService,  # Forced alignment service
    source_service: SourceService,  # Source service for audio paths/text
    seg_urls: SegmentationUrls,  # Segmentation URL bundle
    prefix: str,  # Route prefix (e.g., "/fa")
) -> Tuple[APIRouter, Dict[str, Callable]]:  # (router, route_dict)
    """Initialize forced alignment routes."""
    router = APIRouter(prefix=prefix)

    @router
    async def trigger(request, sess):
        """Trigger forced alignment."""
        return await _handle_fa_trigger(
            state_store, workflow_id, fa_service, source_service,
            request, sess, seg_urls,
            toggle_url=toggle.to(),
        )

    @router
    async def progress(request, sess):
        """Poll forced alignment progress."""
        # Check if FA is still running by checking plugin progress
        proxy = fa_service._manager.get_plugin(fa_service._plugin_name)
        if proxy:
            try:
                prog = await proxy.get_progress_async()
                if prog and prog.get("progress", 0) < 1.0:
                    return render_fa_progress(
                        progress_val=prog["progress"],
                        message=prog.get("message", "Processing..."),
                        progress_url=progress.to(),
                    )
            except Exception:
                pass

        # FA is done or not running — show trigger button
        return render_fa_trigger_button(trigger.to())

    @router
    async def toggle(request, sess):
        """Toggle between NLTK and force-aligned pre-splits."""
        return await _handle_fa_toggle(
            state_store, workflow_id,
            request, sess, seg_urls,
            toggle_url=toggle.to(),
        )

    routes = {
        "trigger": trigger,
        "progress": progress,
        "toggle": toggle,
    }

    return router, routes
