"""Forced alignment service for audio-informed text pre-splitting via forced alignment plugin"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/services/forced_alignment.ipynb.

# %% auto #0
__all__ = ['map_fa_words_to_text', 'assign_words_to_chunks', 'build_segments_from_alignment', 'ForcedAlignmentService']

# %% ../../nbs/services/forced_alignment.ipynb #cell-imports
import re
import asyncio
from typing import List, Dict, Any, Optional, Tuple

from cjm_plugin_system.core.manager import PluginManager

from cjm_transcription_plugin_system.forced_alignment_core import ForcedAlignItem, ForcedAlignResult
from cjm_transcript_segmentation.models import TextSegment
from cjm_transcript_vad_align.models import VADChunk

# %% ../../nbs/services/forced_alignment.ipynb #cell-strip-punct
# Regex to strip punctuation for comparison (matches what FA models strip)
_PUNCT_RE = re.compile(r'[^\w\s]', re.UNICODE)


def _strip_punct(text: str) -> str:
    """Strip punctuation from text for comparison with FA output."""
    return _PUNCT_RE.sub('', text)

# %% ../../nbs/services/forced_alignment.ipynb #cell-map-words
def map_fa_words_to_text(
    text: str,  # Original text with punctuation
    fa_items: List[ForcedAlignItem],  # FA word-level alignment results
) -> List[Tuple[int, int]]:  # List of (start_char, end_char) spans into original text
    """Map forced alignment words back to character spans in the original text.
    
    Walks through the original text, matching each FA word (punctuation-stripped)
    against original text tokens. Returns character offset pairs for each FA word.
    """
    spans = []
    pos = 0  # Current position in original text
    
    for item in fa_items:
        fa_word = item.text.lower()
        
        # Skip whitespace to find next token start
        while pos < len(text) and text[pos].isspace():
            pos += 1
        
        if pos >= len(text):
            break
        
        # Find the end of the current token in original text
        # A token is a run of non-space characters
        token_start = pos
        token_end = pos
        while token_end < len(text) and not text[token_end].isspace():
            token_end += 1
        
        orig_token = text[token_start:token_end]
        stripped_token = _strip_punct(orig_token).lower()
        
        # Check if FA word matches this token (after stripping punctuation)
        if stripped_token == fa_word:
            spans.append((token_start, token_end))
            pos = token_end
        else:
            # Handle multi-token FA words (e.g., "p.m." → "pm") or
            # cases where the original has punctuation splitting tokens
            # Try consuming multiple tokens until the stripped concatenation matches
            concat = stripped_token
            scan_end = token_end
            matched = False
            
            # Try up to 3 extra tokens for cases like "p.m." → "p" + "." + "m" + "."
            for _ in range(3):
                if concat.lower() == fa_word:
                    spans.append((token_start, scan_end))
                    pos = scan_end
                    matched = True
                    break
                # Skip whitespace
                while scan_end < len(text) and text[scan_end].isspace():
                    scan_end += 1
                if scan_end >= len(text):
                    break
                # Consume next token
                next_start = scan_end
                while scan_end < len(text) and not text[scan_end].isspace():
                    scan_end += 1
                concat += _strip_punct(text[next_start:scan_end])
            
            if not matched:
                # Check final concatenation
                if concat.lower() == fa_word:
                    spans.append((token_start, scan_end))
                    pos = scan_end
                else:
                    # Fallback: skip this original token and try again
                    # (handles insertions/deletions between transcript and FA output)
                    spans.append((token_start, token_end))
                    pos = token_end
    
    return spans

# %% ../../nbs/services/forced_alignment.ipynb #cell-assign-chunks
def assign_words_to_chunks(
    fa_items: List[ForcedAlignItem],  # FA word-level alignment results
    vad_chunks: List[VADChunk],  # VAD chunks with start/end times
) -> List[int]:  # Chunk index for each FA word
    """Assign each FA word to a VAD chunk based on timestamp overlap.
    
    Words whose start_time falls within a chunk's [start, end] range are
    assigned to that chunk. Words in silence gaps are assigned to the
    nearest chunk by time proximity.
    """
    if not vad_chunks:
        return [0] * len(fa_items)
    
    assignments = []
    
    for item in fa_items:
        t = item.start_time
        best_idx = 0
        best_dist = float('inf')
        contained = False
        
        for i, chunk in enumerate(vad_chunks):
            # Strict containment (no tolerance)
            if chunk.start_time <= t <= chunk.end_time:
                best_idx = i
                contained = True
                break
            
            # Track nearest chunk for gap assignment
            dist = min(abs(t - chunk.start_time), abs(t - chunk.end_time))
            if dist < best_dist:
                best_dist = dist
                best_idx = i
        
        assignments.append(best_idx)
    
    return assignments

# %% ../../nbs/services/forced_alignment.ipynb #cell-build-segments
def build_segments_from_alignment(
    text: str,  # Original text with punctuation
    spans: List[Tuple[int, int]],  # Character spans from map_fa_words_to_text
    assignments: List[int],  # Chunk index per word from assign_words_to_chunks
    num_chunks: int,  # Total number of VAD chunks
    source_id: Optional[str] = None,  # Source block ID for traceability
    source_provider_id: Optional[str] = None,  # Source provider identifier
) -> List[TextSegment]:  # One segment per VAD chunk
    """Build TextSegment list by grouping words by their assigned VAD chunk.
    
    Each VAD chunk gets one TextSegment whose text is the joined original
    (punctuated) words assigned to that chunk.
    """
    # Group spans by chunk assignment
    chunk_spans: Dict[int, List[Tuple[int, int]]] = {}
    for span, chunk_idx in zip(spans, assignments):
        if chunk_idx not in chunk_spans:
            chunk_spans[chunk_idx] = []
        chunk_spans[chunk_idx].append(span)
    
    segments = []
    for chunk_idx in range(num_chunks):
        word_spans = chunk_spans.get(chunk_idx, [])
        
        if word_spans:
            # Extract text from original using spans
            # Use the full range from first word start to last word end
            seg_start = word_spans[0][0]
            seg_end = word_spans[-1][1]
            seg_text = text[seg_start:seg_end].strip()
        else:
            # Empty segment (VAD chunk with no assigned words)
            seg_text = ""
            seg_start = None
            seg_end = None
        
        segments.append(TextSegment(
            index=chunk_idx,
            text=seg_text,
            source_id=source_id,
            source_provider_id=source_provider_id,
            start_char=seg_start,
            end_char=seg_end,
        ))
    
    return segments

# %% ../../nbs/services/forced_alignment.ipynb #cell-service
class ForcedAlignmentService:
    """Service for audio-informed text pre-splitting via forced alignment plugin."""

    def __init__(
        self,
        plugin_manager: PluginManager,  # Plugin manager for accessing forced alignment plugin
        plugin_name: str = "cjm-transcription-plugin-qwen3-forced-aligner",  # Name of the FA plugin
    ):
        """Initialize the forced alignment service."""
        self._manager = plugin_manager
        self._plugin_name = plugin_name

    def is_available(self) -> bool:  # True if plugin is loaded and ready
        """Check if the forced alignment plugin is available."""
        return self._manager.get_plugin(self._plugin_name) is not None

    def ensure_loaded(
        self,
        config: Optional[Dict[str, Any]] = None,  # Optional plugin configuration
    ) -> bool:  # True if successfully loaded
        """Ensure the forced alignment plugin is loaded."""
        if self.is_available():
            return True
        meta = self._manager.get_discovered_meta(self._plugin_name)
        if meta:
            return self._manager.load_plugin(meta, config or {"language": "English"})
        return False

    async def align_and_split_async(
        self,
        audio_path: str,  # Path to the audio file
        text: str,  # Original transcript text blob (with punctuation)
        vad_chunks: List[VADChunk],  # VAD chunks for this audio
        source_id: Optional[str] = None,  # Source block ID for traceability
        source_provider_id: Optional[str] = None,  # Source provider identifier
    ) -> List[TextSegment]:  # One segment per VAD chunk
        """Run forced alignment and split text into segments matching VAD chunks."""
        if not self.is_available():
            raise RuntimeError(f"Plugin {self._plugin_name} not loaded")

        # 1. Call forced alignment plugin
        result = await self._manager.execute_plugin_async(
            self._plugin_name,
            audio=audio_path,
            text=text,
        )

        # Convert dict result to ForcedAlignItem objects
        items = [
            ForcedAlignItem(**item_dict)
            for item_dict in result.get("items", [])
        ]

        # 2. Map FA words back to original text positions
        spans = map_fa_words_to_text(text, items)

        # 3. Assign words to VAD chunks
        assignments = assign_words_to_chunks(items, vad_chunks)

        # 4-5. Group by chunk and build TextSegments
        segments = build_segments_from_alignment(
            text=text,
            spans=spans,
            assignments=assignments,
            num_chunks=len(vad_chunks),
            source_id=source_id,
            source_provider_id=source_provider_id,
        )

        return segments

    def align_and_split(
        self,
        audio_path: str,  # Path to the audio file
        text: str,  # Original transcript text blob
        vad_chunks: List[VADChunk],  # VAD chunks for this audio
        source_id: Optional[str] = None,
        source_provider_id: Optional[str] = None,
    ) -> List[TextSegment]:  # One segment per VAD chunk
        """Run forced alignment and split text synchronously."""
        return asyncio.get_event_loop().run_until_complete(
            self.align_and_split_async(
                audio_path, text, vad_chunks, source_id, source_provider_id
            )
        )

    async def align_and_split_combined_async(
        self,
        source_blocks: List[Any],  # SourceBlock objects with id, provider_id, text
        audio_paths: List[str],  # Audio file path per source block
        vad_chunks_by_source: List[List[VADChunk]],  # VAD chunks per source block
    ) -> List[TextSegment]:  # Combined segments with global indexing
        """Align and split multiple source blocks with their respective audio."""
        all_segments = []
        global_index = 0

        for block, audio_path, chunks in zip(source_blocks, audio_paths, vad_chunks_by_source):
            segments = await self.align_and_split_async(
                audio_path=audio_path,
                text=block.text,
                vad_chunks=chunks,
                source_id=block.id,
                source_provider_id=block.provider_id,
            )
            for seg in segments:
                seg.index = global_index
                global_index += 1
                all_segments.append(seg)

        return all_segments
