"""Data types and result containers for the segment-align integration surface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/models.ipynb.

# %% auto #0
__all__ = ['SegmentAlignUrls', 'SegmentAlignResult']

# %% ../nbs/models.ipynb #efa2737a
from typing import Callable, Dict, Any, List, Optional
from dataclasses import dataclass, field

from cjm_transcript_segmentation.models import SegmentationUrls
from cjm_transcript_vad_align.models import AlignmentUrls

# %% ../nbs/models.ipynb #b3eceaa7
@dataclass
class SegmentAlignUrls:
    """Combined URL bundle for host access."""
    seg: SegmentationUrls = None           # Segmentation route URLs
    align: AlignmentUrls = None            # Alignment route URLs
    switch_chrome: str = ""                 # Chrome switching URL
    fa_toggle: str = ""                     # FA toggle URL (empty if FA unavailable)

# %% ../nbs/models.ipynb #02fbf7e3
@dataclass
class SegmentAlignResult:
    """Everything the host needs from init_segment_align_routers()."""
    urls: SegmentAlignUrls                          # Combined URL bundle
    render_step: Callable                            # fn(ctx: InteractionContext) -> FT
    sse_headers: list = field(default_factory=list)  # Headers for app (SSE extension)
    fa_available: bool = False                       # Whether forced alignment is available
    validate_alignment: Callable = None              # fn(state: dict) -> bool
